services:
  sshpasslog:
    container_name: sshpasslog
    build:
      context: .
      target: app
      args:
        HOST_UID: ${HOST_UID:?err}
        HOST_GID: ${HOST_GID:?err}
    init: true
    restart: unless-stopped
    network_mode: host  # Otherwise client_ip is 172.x.x.x
    volumes:
      - ./src/:/app/src/:ro
      - ./host_keys/:/app/host_keys/:ro
      - ./sshpasslog.sqlite3:/app/sshpasslog.sqlite3:rw
      - ./sshpasslog.log:/app/sshpasslog.log:rw
