[tool.poetry]
name = "sshpasslog"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
paramiko = "^3.2.0"
ip3country = "^0.2.0"


[tool.poetry.group.dev.dependencies]
types-paramiko = "^3.2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
